In [ ]:
Seudocódigo que realiza 
a) la eliminación hacia adelante y 
b) la sustitución hacia atrás.
a)       
DOFOR k = 1, n — 1         
    DOFOR i = k + 1, n           
        factor = ai,k / ak,k             
            DOFOR j = k + 1 to n               
                ai,j = ai,j — factor · ak,j            
            END DO             
        bi = bi — factor · bk         
    END DO          
END DO 
b)      
xn = bn / an,n          
    DOFOR i = n — 1, 1, —1         
        sum = bi         
            DOFOR j = i + 1, n            
                sum = sum – ai,j · xj            
            END DO             
        xi = sum / ai,i          
    END DO

In [2]:
import numpy
m=int(input("Valor de m:"))
n=int(input("Valor de n:"))
matrix = numpy.zeros((m,n))
vector= numpy.zeros((n))
x=numpy.zeros((m))
print( 'Introduce la matriz de coeficientes y el vector solución')
for r in range(0,m):
    for c in range(0,n):
        
        matrix[(r),(c)]=(input("Elemento a["+str(r+1)+","+str(c+1)+"]  "))
        
    vector[(r)]=(input("b["+str(r+1)+"]"))
             
print (matrix)
                 
for k in range(0,m):
    for r in range(k+1,m):
        factor=(matrix[r,k]/matrix[k,k])
        vector[r]=vector[r]-(factor*vector[k])
        for c in range(0,n):
            matrix[r,c]=matrix[r,c]-(factor*matrix[k,c])


#sustitución hacia atrás
x[m-1]=vector[m-1]/matrix[m-1,m-1]
print (x[m-1])
for r in range(m-2,-1,-1):
    suma=0
    for c in range(0,n):
        suma=suma+matrix[r,c]*x[c]
    x[r]=(vector[r]-suma)/matrix[r,r]
print ('Resultado matriz')
print(matrix)
print ('Resultado del vector')
print(vector)
print ('Resultados de la forma x1+x2+x3: ')
print(x)

Valor de m:3
Valor de n:3
Introduce la matriz de coeficientes y el vector solución
Elemento a[1,1]  3
Elemento a[1,2]  -0.1
Elemento a[1,3]  -0.2
b[1]7.85
Elemento a[2,1]  0.1
Elemento a[2,2]  7
Elemento a[2,3]  -0.3
b[2]-19.3
Elemento a[3,1]  0.3
Elemento a[3,2]  -0.2
Elemento a[3,3]  10
b[3]71.4
[[  3.   -0.1  -0.2]
 [  0.1   7.   -0.3]
 [  0.3  -0.2  10. ]]
7.0
Resultado matriz
[[  3.          -0.1         -0.2       ]
 [  0.           7.00333333  -0.29333333]
 [  0.           0.          10.01204188]]
Resultado del vector
[  7.85       -19.56166667  70.08429319]
Resultados: 
[ 3.  -2.5  7. ]
